version: '3'

vars:
  PROJECT_NAME: wool-witch
  NODE_VERSION: '>=18.0.0'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  install:
    desc: Install project dependencies
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/**/*

  dev:
    desc: Start development server with hot reload
    deps: [install]
    cmds:
      - npm run dev

  build:
    desc: Build the project for production
    deps: [install]
    cmds:
      - npm run build
    sources:
      - src/**/*
      - index.html
      - vite.config.ts
      - tsconfig*.json
    generates:
      - dist/**/*

  lint:
    desc: Run ESLint to check code quality
    deps: [install]
    cmds:
      - npm run lint

  lint:fix:
    desc: Run ESLint and automatically fix issues
    deps: [install]
    cmds:
      - npm run lint -- --fix

  typecheck:
    desc: Run TypeScript type checking
    deps: [install]
    cmds:
      - npm run typecheck

  preview:
    desc: Preview production build locally
    deps: [build]
    cmds:
      - npm run preview

  clean:
    desc: Remove build artifacts and dependencies
    cmds:
      - rm -rf dist || true
      - rm -rf node_modules || true
      - rm -rf .vite || true
      - echo "âœ… Cleaned build artifacts and dependencies"

  clean:dist:
    desc: Remove only build artifacts (keeps node_modules)
    cmds:
      - rm -rf dist || true
      - rm -rf .vite || true
      - echo "âœ… Cleaned build artifacts"

  setup:
    desc: Complete first-time project setup
    cmds:
      - task: check-env
      - task: install
      - echo "âœ… Setup complete! Run 'task dev' to start developing."

  check-env:
    desc: Check if required environment variables are set
    cmds:
      - |
        if [ ! -f .env ]; then
          if [ ! -f .env.example ]; then
            echo "âš ï¸  .env and .env.example not found. Creating .env.example..."
            cat > .env.example <<EOF
        # Supabase Configuration
        # Get these values from your Supabase project settings
        VITE_SUPABASE_URL=your_supabase_url_here
        VITE_SUPABASE_ANON_KEY=your_supabase_anon_key_here
        EOF
          fi
          echo "âš ï¸  .env file not found."
          echo "ðŸ“ Please copy .env.example to .env and fill in your Supabase credentials"
          echo "   You can get these from: https://app.supabase.com/project/_/settings/api"
          exit 1
        else
          echo "âœ… .env file exists"
        fi
    silent: true

  test:
    desc: Run all quality checks (lint, typecheck)
    deps: [install]
    cmds:
      - task: lint
      - task: typecheck
      - echo "âœ… All checks passed!"

  ci:
    desc: Run all CI checks (used in continuous integration)
    cmds:
      - task: install
      - task: test
      - task: build
